extends SceneTree

const History = preload("res://scripts/history_store.gd")
const Tracking = preload("res://scripts/tracking_state.gd")
const Scores = preload("res://scripts/score_store.gd")
const Room = preload("res://scripts/practice_room.gd")


func _init() -> void:
	var prefix := "user://history-check-%d" % Time.get_ticks_usec()
	var path := prefix + ".json"
	var history = History.new(path)
	assert(history.load_history())
	var record := History.snapshot("color", [100000, 200000, 300000, 400000, 500000], 1.25)
	assert(history.save_record(record, "  mouse-A  "))
	assert(not history.save_record(record, "mouse-A"))
	assert(history.records.size() == 1)
	var loaded = History.new(path)
	assert(loaded.load_history())
	for index in 5:
		assert(int(loaded.records[0].samples[index]) == record.samples[index])
	assert(loaded.records[0].local_time == record.local_time)
	assert(absf(loaded.records[0].timestamp_utc - record.timestamp_utc) < 0.001)
	assert(loaded.records[0].tag == "mouse-A")
	assert(loaded.filtered("color", "mouse-A").size() == 1)
	assert(loaded.filtered("osu").is_empty())
	assert(loaded.filtered("color", "mouse-B").is_empty())
	var future := record.duplicate(true)
	future.id += "-v2"
	future.rule_version = 2
	assert(history.save_record(future, ""))
	assert(history.filtered("color").size() == 1)
	assert(history.filtered("color", "", 2).size() == 1)
	var tracking_record := History.snapshot("tracking", [0.0, 10.0, 50.0, 90.0, 100.0], 1.0, [20.0, 10.0, 5.0, 1.0, 0.0])
	assert(history.save_record(tracking_record, "tracking"))
	assert(loaded.load_history())
	assert(loaded.filtered("tracking")[0].stats.median == 50.0)
	var invalid := record.duplicate(true)
	invalid.samples = [1, 2]
	assert(not History.valid_record(invalid))
	invalid = record.duplicate(true)
	invalid.local_time = "2026-99-99 99:99:99"
	assert(not History.valid_record(invalid))
	invalid = record.duplicate(true)
	invalid.stats.median = 999
	assert(not History.valid_record(invalid))
	invalid = record.duplicate(true)
	invalid.samples[0] = NAN
	assert(not History.valid_record(invalid))
	var blocked = History.new(prefix + "/missing/history.json")
	assert(not blocked.save_record(record, ""))
	assert(blocked.records.is_empty())
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string("broken history")
	file.close()
	assert(not loaded.load_history())
	assert(not loaded.save_record(record, ""))
	assert(FileAccess.get_file_as_string(path) == "broken history")
	file = FileAccess.open(path, FileAccess.WRITE)
	file.store_string('{"version": 2, "records": []}')
	file.close()
	assert(not loaded.load_history())
	assert(not loaded.writable)
	DirAccess.remove_absolute(path)

	var scores = Scores.new()
	scores.score_path = prefix + "-scores.txt"
	file = FileAccess.open(scores.score_path, FileAccess.WRITE)
	file.store_string("color 250.0\nshooter 300.0\nosu 1000.0\nspheres 1500.0\nlook_sens 1.25\n")
	file.close()
	scores.load_scores()
	assert(scores.color == 250.0 and scores.tracking == -1.0)
	assert(scores.update("tracking", 0.0))
	assert(not scores.update("tracking", 0.0))
	assert(scores.update("tracking", 60.0))
	assert(not scores.update("tracking", 50.0))
	assert(not scores.update("tracking", 101.0))
	assert(not scores.update("color", NAN))
	assert(scores.update("color", 200.0))
	var read_scores = Scores.new()
	read_scores.score_path = scores.score_path
	read_scores.load_scores()
	assert(read_scores.tracking == 60.0 and read_scores.color == 200.0)
	scores.score_path = prefix + "/missing/scores.txt"
	assert(not scores.update("tracking", 70.0))
	assert(scores.tracking == 60.0, "failed writes must roll back in memory")
	DirAccess.remove_absolute(read_scores.score_path)

	var state = Tracking.new()
	state.prepare(100)
	assert(not state.advance(state.deadline_us - 1, true, 0.0))
	assert(state.covered_us == 0)
	for round_index in 5:
		state.advance(state.deadline_us, true, 0.0)
		assert(state.stage == Tracking.Stage.ACTIVE)
		var start: int = state.start_us
		state.advance(start + 2_000_000, true, 2.0)
		state.advance(start + 9_000_000, false, 12.0)
		assert(state.advance(start + 11_000_000, true, 2.0))
		assert(state.coverage[round_index] == 30.0)
		assert(is_equal_approx(state.errors[round_index], 9.0))
	assert(state.stage == Tracking.Stage.SUMMARY)
	assert(History.valid_record(History.snapshot("tracking", state.coverage, 1.0, state.errors)))
	state.reset()
	state.prepare(0)
	state.advance(Tracking.PREP_US, false, 0.0)
	state.advance(state.start_us + Tracking.ROUND_US, false, 180.0)
	assert(state.coverage[0] == 0.0)
	state.advance(state.deadline_us, true, 0.0)
	state.advance(state.start_us + Tracking.ROUND_US, true, 0.0)
	assert(state.coverage[1] == 100.0)
	var origin := Vector3(0, 1.4, 0)
	assert(Tracking.is_covered(origin, Vector3.FORWARD, Vector3(0, 1.4, -8)))
	assert(not Tracking.is_covered(origin, Vector3.FORWARD, Vector3(0.43, 1.4, -8)))
	assert(not Tracking.is_covered(origin, Vector3.FORWARD, Vector3(0, 1.4, 8)))
	for round_index in 5:
		for step in 1001:
			var position := Tracking.target_position(round_index, step / 100.0)
			assert(Room.contains_point(position, Tracking.RADIUS))
			assert(position == Tracking.target_position(round_index, step / 100.0))
			assert(Tracking.is_covered(origin, (position - origin).normalized(), position))
	print("history_tracking_test: PASS")
	quit()
